name: Default Workflow

on: workflow_dispatch

jobs:
  npm-job:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '10'
    - name: Install NPM dependencies
      run: npm install

  python-job:
    needs: npm-job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Python script
      run: python driver/execute_analysis.py
